<?php

namespace Database\Seeders;

use App\Models\Ingredient;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $name = [
            'Orange',
            'Dough',
            'Sauce',
            'Cheese',
            'Toppings: Meats',
            'Vegetables',
            'Shrimp ',
            'Shrimp Broth',
            'Vegetables',
            'Spices',
            'Beef',
            'zucchini',
            'carrots',
            'green pepper',
            'broccoli',
            'spinach',
            'molokhia',
            'bulgur',
            'onions',
            'eggs',
            'garlic',
            'herbs',
            'salt',
            ' spices.',
            'shots of espresso',
            'steamed milk',
            'a thin layer of foamed milk.',
            'Lettuce',
            'tomato',
            'mushroom',
            'carrot',
            'sweet corn',
            'black olives',
            'cocktail sauce',
            'Halal frozen beef',
            'water',
            'salt',
            'onion',
            'garlic',
            'spices',
            'carbohydrates',
            'phosphates (E450, E451, E452)',
            'protein',
            'Fresh chicken',
            'Assorted vegetables: such as onions',
            'garlic, green peppers',
            'red peppers',
            ' eggplant',
            ' zucchini',
            'carrots',
            'coriander',
            ' Olive oil',
            'Spices and seasonings: such as salt',
            'black pepper',
            ' garlic powder',
            ' cumin seeds',
            'dried coriander',
            'any other spices that add a delicious flavor to the meal',
            ' Lemon juice: can be added to add a refreshing flavor.',
            ' whole chicken (about 1.5 - 2 kg)',
            ' olive oil',
            ' juice of  lemon',
            'minced garlic',
            '  paprika',
            '  cumin',
            ' dried coriander',
            'salt and pepper to taste',
            '250 grams of pasta (such as spaghetti fusilli or any type you prefer)',
            'olive oil',
            'garlic',
            ' minced',
            ' onion',
            'minced',
            'cut into cubes',
            'chopped tomatoes (can use canned tomatoes)',
            'dried herbs (such as oregano or basil)',
            ' grated Parmesan cheese (optional for serving)',
            'rice noodles or regular noodles',
            'chicken breast',
            ' sliced',
            ' cups mixed vegetables (such as carrots, peppers, broccoli)',
            'tablespoons soy sauce and  teaspoon sesame oil',

            ' boiled eggs',
            'slices of bread (wholemeal bread can be used)',
            '  salt and pepper to taste',
            'sliced ​​cucumber or tomato (optional)',
            'teaspoon mayonnaise or yogurt (optional)',

            ' cup fresh spinach',
            'avocado',
            'chopped cucumber',
            'tablespoon lemon juice',
            'handful of nuts (such as almonds or walnuts)'
        ];
        $name_ar = [
            'برتقال',
            'العجين ',
            'الصلصة ',
            ' الجبن ',
            'الإضافات: اللحوم ',
            'الخضروات',
            'الروبيان',
            'مرق الروبيان',
            'الخضار',
            'لبهارات ',

            ' لحم بقري',
            ' كوسة',
            ' جزر',
            ' فلفل',
            'أخضر ',
            ' بروكلي',
            ' سبانخ',
            ' ملوخية',
            ' برغل',
            'بصل',
            '   بيض',
            'ثوم',
            '  أعشاب',
            'بهارات.',
            ' الاسبريسو',
            ' حليب مبخر وتعلوهم ',
            'طبقة رقيقة من الحليب الرغوي',
            'خس ',
            'طماطم ',
            ' فطر ',
            'جزر ',
            'ذرة حلوة ',
            ' زيتون أسود ',
            'صلصة الكوكتيل',
            'لحم بقري مجمد حلال',
            'ماء',
            'ملح',
            'بصل',
            'ثوم',
            'بهارات',
            'كربوهيدرات',
            '  فوسفات (E450، E451، E452)',
            ' بروتين.',
            'دجاج طازج ',
            'خضروات متنوعة: مثل البصل',
            'الثوم',
            'الفلفل الأخضر',
            'الفلفل الأحمر الباذنجان',
            'الكوسا',
            'الجزر',
            ' الكزبرة',
            '  زيت الزيتون',
            'التوابل والبهارات: مثل الملح',
            ' الفلفل الأسود',
            ' بودرة الثوم',
            'بذور الكمون',
            'الكزبرة المجففة',
            ' أو أي توابل أخرى تضيف نكهة لذيذة للوجبة',
            ' عصير الليمون: يمكن إضافته لإضافة نكهة منعشة.',
            'دجاجة كاملة (حوالي 1.5 - 2 كجم)',
            ' ملاعق كبيرة زيت زيتون ',
            'عصير ليمونة واحدة ',
            'فصوص ثوم مفروم ',
            'ملعقة صغيرة من البابريكا',
            ' ملعقة صغيرة من الكمون ',
            '  ملعقة صغيرة من الكزبرة المجففة ',
            'ملح وفلفل حسب الذوق',
            ' غرام من المعكرونة (مثل السباغيتي أو الفوسيلي أو أي نوع تفضله) ',
            '  ملعقة كبيرة من زيت الزيتون ',
            '  فصوص ثوم مفرومة',
            ' حبة بصل متوسطة مفرومة',
            ' حبة فلفل رومي (أي لون) مقطعة إلى مكعبات ',
            ' كوب من الطماطم المقطعة (يمكن استخدام الطماطم المعلبة)',
            ' ملعقة صغيرة من الأعشاب المجففة (مثل الأوريجانو أو الريحان) ',
            'جبنة بارميزان مبشورة (اختياري للتقديم)',
            'بصل',
            'ثوم',
            ' غرام من نودلز الأرز أو النودلز العادية ',
            ' غرام من صدور الدجاج',
            ' مقطعة إلى شرائح ',
            'كوب من الخضار المشكّلة (مثل الجزر والفلفل والبروكلي) ',
            ' ملاعق كبيرة من صوص الصويا وملعقة صغيرة من زيت السمسم',
            ' بيضة مسلوقة ',
            'شريحتان من الخبز (يمكن استخدام الخبز الكامل)',
            'ملح وفلفل حسب الذوق ',
            'شرائح خيار أو طماطم (اختياري)',
            ' ملعقة صغيرة من المايونيز أو الزبادي (اختياري)',
            'كوب من السبانخ الطازجة ',
            'نصف حبة أفوكادو',
            'حبة خيار مقطعة',
            'ملعقة كبيرة من عصير الليمون',
            ' حفنة من المكسرات (مثل اللوز أو الجوز)'
        ];
        $meal = [1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13];
        for ($i = 0; $i < count($meal); $i++) {
            Ingredient::create([
                'name' => $name[$i],
                'name_ar' => $name_ar[$i],
                'num' => rand(1, 100),
                'meal_id' => $meal[$i],
            ]);
        }
    }
}
